import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BadgeCheck, Banknote, Building2, Check, CircleDollarSign, ClipboardList, ExternalLink, HandHeart, Heart, MapPin, Menu, Pencil, Search, ShieldCheck, Store, Users, X } from 'lucide-react';

type Campaign = { id:number; title:string; summary:string; status:'Активна'|'Предстояща'|'Завършена'; raised:number; goal:number };
type Partner = { id:number; name:string; area:string; hasBox:boolean };

const defaultCampaigns: Campaign[] = [
 {id:1,title:'Тук ще бъде публикувана активна кампания',summary:'Екипът на „Банско за теб“ ще добавя проверена информация, цел и актуален напредък.',status:'Активна',raised:0,goal:100},
 {id:2,title:'Следваща кауза',summary:'Подготвено място за следваща одобрена инициатива на фондацията.',status:'Предстояща',raised:0,goal:100}
];
const demoPartners: Partner[] = [
 {id:1,name:'Партньорски обект 01',area:'Център',hasBox:true},{id:2,name:'Партньорски обект 02',area:'Стария град',hasBox:true},{id:3,name:'Партньорски обект 03',area:'Квартал Новия град',hasBox:true},{id:4,name:'Партньорски обект 04',area:'Център',hasBox:true}
];
const nav = [['Начало','home'],['Кампании','campaigns'],['Дарения','donate'],['Кутии за дарения','boxes'],['Прозрачност','transparency'],['За нас','about']];
function money(value:number){return new Intl.NumberFormat('bg-BG',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value)}

export default function Portal(){
 const [menuOpen,setMenuOpen]=useState(false); const [dashboardOpen,setDashboardOpen]=useState(false); const [search,setSearch]=useState(''); const [campaigns,setCampaigns]=useState<Campaign[]>(defaultCampaigns); const [editingId,setEditingId]=useState<number|null>(null); const [draftTitle,setDraftTitle]=useState(''); const [saved,setSaved]=useState(false);
 useEffect(()=>{const stored=localStorage.getItem('bansko-za-teb-demo-campaigns');if(stored){try{setCampaigns(JSON.parse(stored) as Campaign[])}catch{setCampaigns(defaultCampaigns)}}},[]);
 const filteredPartners=useMemo(()=>{const term=search.trim().toLocaleLowerCase('bg');if(!term)return demoPartners;return demoPartners.filter(p=>`${p.name} ${p.area}`.toLocaleLowerCase('bg').includes(term))},[search]);
 function goTo(id:string){setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
 function editCampaign(c:Campaign){setEditingId(c.id);setDraftTitle(c.title);setSaved(false)}
 function saveCampaign(){const clean=draftTitle.trim();if(!clean||editingId===null)return;const next=campaigns.map(c=>c.id===editingId?{...c,title:clean}:c);setCampaigns(next);localStorage.setItem('bansko-za-teb-demo-campaigns',JSON.stringify(next));setEditingId(null);setDraftTitle('');setSaved(true)}
 function resetDemo(){setCampaigns(defaultCampaigns);localStorage.removeItem('bansko-za-teb-demo-campaigns');setEditingId(null);setSaved(false)}
 return <div className="portal-shell">
  <header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>goTo('home')}><span className="brand-mark"><Heart size={20}/></span><span><strong>Банско</strong> за теб</span></button><nav className="desktop-nav">{nav.map(([label,id])=><button key={id} onClick={()=>goTo(id)}>{label}</button>)}</nav><div className="header-actions"><button className="ghost-btn dashboard-btn" onClick={()=>setDashboardOpen(true)}>Табло</button><button className="primary-btn compact" onClick={()=>goTo('donate')}>Дарете</button><button className="menu-btn" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button></div></div>{menuOpen&&<div className="mobile-nav">{nav.map(([label,id])=><button key={id} onClick={()=>goTo(id)}>{label}<ArrowRight size={16}/></button>)}<button onClick={()=>{setMenuOpen(false);setDashboardOpen(true)}}>Табло за екипа <ArrowRight size={16}/></button></div>}</header>
  <main>
   <section className="hero" id="home"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><HandHeart size={16}/> Обединени в доброто</div><h1>Помощта е най-силна, когато сме <span>заедно.</span></h1><p>Едно място за каузите на „Банско за теб“, проверена информация, начини за дарение и бизнесите в града, където има официална кутия за дарения.</p><div className="hero-buttons"><button className="primary-btn" onClick={()=>goTo('campaigns')}>Виж кампаниите <ArrowRight size={18}/></button><button className="secondary-btn" onClick={()=>goTo('boxes')}><MapPin size={18}/> Намери кутия</button></div><div className="trust-row"><span><ShieldCheck size={18}/> Проверени кампании</span><span><ClipboardList size={18}/> Публични отчети</span><span><BadgeCheck size={18}/> Официални партньори</span></div></div><div className="hero-card"><div className="hero-card-head"><span className="live-dot"/><span>Портал за каузи</span><span className="status-chip">Работна версия</span></div><div className="impact-card"><Heart size={30}/><div><small>Една общност</small><strong>Една добра посока</strong><p>Дарение, доброволчество, споделяне или просто подкрепа.</p></div></div><div className="mini-grid"><div><Store/><strong>Кутии</strong><span>в партньорски обекти</span></div><div><Banknote/><strong>Дарения</strong><span>директно към каузата</span></div><div><Users/><strong>Общност</strong><span>хора и бизнеси</span></div><div><ShieldCheck/><strong>Доверие</strong><span>ясна отчетност</span></div></div></div></div></section>
   <div className="work-notice"><div><ShieldCheck size={20}/><span><strong>Тестова публична версия.</strong> Банковите данни, реалните кампании и партньорските обекти ще бъдат публикувани само след потвърждение от екипа.</span></div></div>
   <section className="section" id="campaigns"><div className="section-heading split-heading"><div><span className="section-kicker">Кампании</span><h2>Каузи, които имат нужда от нас</h2><p>Всяка реална кампания ще съдържа история, необходима сума, актуален напредък, документи и отчет за резултата.</p></div><button className="text-link" onClick={()=>setDashboardOpen(true)}>Управление от екипа <ArrowRight size={17}/></button></div><div className="campaign-grid">{campaigns.map(c=>{const percent=Math.min(100,Math.round(c.raised/c.goal*100));return <article className="campaign-card" key={c.id}><div className="campaign-visual"><Heart size={34}/><span>{c.status}</span></div><div className="campaign-content"><h3>{c.title}</h3><p>{c.summary}</p><div className="progress-meta"><span>Събрани {money(c.raised)}</span><span>{percent}%</span></div><div className="progress-track"><span style={{width:`${percent}%`}}/></div><div className="campaign-footer"><span>Цел: {money(c.goal)}</span><button onClick={()=>goTo('donate')}>Подкрепи <ArrowRight size={16}/></button></div></div></article>})}</div></section>
   <section className="section soft-section" id="donate"><div className="section-heading centered"><span className="section-kicker">Дарения</span><h2>Изберете най-удобния начин да помогнете</h2><p>Без посредници и без скрити такси в портала. Реалните банкови данни ще бъдат въведени от организацията преди официалното пускане.</p></div><div className="donation-grid"><article className="donation-card featured"><Building2/><div><span className="recommended">Препоръчано</span><h3>Банков превод</h3><p>Директно към официалната сметка на организацията.</p></div><div className="bank-placeholder"><span>IBAN</span><strong>Ще бъде добавен след потвърждение</strong><span>Основание</span><strong>Избрана кампания / Дарение</strong></div></article><article className="donation-card"><Store/><div><h3>Кутия за дарения</h3><p>Дарете на място в проверен партньорски бизнес в Банско.</p></div><button className="card-action" onClick={()=>goTo('boxes')}>Намери най-близката кутия <ArrowRight size={17}/></button></article><article className="donation-card"><HandHeart/><div><h3>Помогнете по друг начин</h3><p>Доброволчество, услуга, транспорт, материали или споделяне на кампания.</p></div><button className="card-action" onClick={()=>goTo('about')}>Свържете се с екипа <ArrowRight size={17}/></button></article></div></section>
   <section className="section" id="boxes"><div className="section-heading split-heading"><div><span className="section-kicker">Кутии за дарения</span><h2>Бизнеси, които застават зад каузата</h2><p>В Bansko.be всеки одобрен бизнес с официална кутия ще получава бадж „Банско за теб“.</p></div><div className="bansko-link"><BadgeCheck/><span>Свързано с <strong>Bansko.be</strong></span></div></div><div className="boxes-layout"><div className="partner-panel"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Търси бизнес или район..."/></div><div className="partner-list">{filteredPartners.map(p=><div className="partner-row" key={p.id}><Store/><div className="partner-copy"><strong>{p.name}</strong><span><MapPin size={13}/> {p.area}</span></div>{p.hasBox&&<div className="cause-badge"><Heart size={13}/> Банско за теб</div>}</div>)}</div><div className="demo-label">Демонстрационни обекти – ще бъдат заменени с реалните записи от Bansko.be.</div></div><div className="map-placeholder"><div className="map-info"><MapPin/><strong>Интерактивна карта</strong><span>Във финалната интеграция локациите идват от бизнес директорията на Bansko.be.</span></div></div></div></section>
   <section className="section transparency" id="transparency"><div className="transparency-inner"><div><span className="section-kicker light">Прозрачност</span><h2>Доверието не се иска. То се показва.</h2><p>Порталът е структуриран така, че посетителят да вижда какво се събира, за какво се използва и какъв е резултатът.</p><div className="check-list"><span><Check/> Ясна цел и статус на всяка кампания</span><span><Check/> История на постъпленията и отчетите</span><span><Check/> Документи и актуализации от екипа</span><span><Check/> Архив на приключените кампании</span></div></div><div className="transparency-card"><div className="report-top"><ClipboardList/> Публичен отчет</div><div className="report-row"><span>Събрани средства</span><strong>След официално публикуване</strong></div><div className="report-row"><span>Разпределени средства</span><strong>След официално публикуване</strong></div><button className="report-btn">Отчети и документи <ExternalLink size={16}/></button></div></div></section>
   <section className="section about-section" id="about"><div className="about-grid"><div><span className="section-kicker">За „Банско за теб“</span><h2>Локална помощ. Реални хора. Видим резултат.</h2></div><div className="about-copy"><p>Порталът е създаден като централен дом на благотворителните инициативи на организацията – място, което свързва нуждаещи се, дарители, доброволци и бизнеса в Банско.</p><p>Съдържанието ще се управлява директно от оторизираните хора на „Банско за теб“, за да остава актуално и проверимо.</p></div></div></section>
   <section className="cta-section"><div><span>Малък жест. Голямо значение.</span><h2>Заедно можем да помогнем навреме.</h2></div><button className="white-btn" onClick={()=>goTo('donate')}>Искам да помогна <ArrowRight/></button></section>
  </main>
  <footer><div className="footer-brand"><span className="brand-mark"><Heart/></span><strong>Банско за теб</strong></div><p>Публичен портал за каузи, дарения и общностна подкрепа в Банско.</p><div className="footer-meta"><span>Работна версия</span><span>Свързано с Bansko.be</span></div></footer>
  {dashboardOpen&&<div className="dashboard-overlay"><div className="dashboard-sheet"><div className="dashboard-top"><div><span className="section-kicker">Демо табло</span><h2>Управление на портала</h2><p>Промените в тази версия се пазят само на текущото устройство.</p></div><button className="close-btn" onClick={()=>setDashboardOpen(false)}><X/></button></div><div className="dashboard-alert"><ShieldCheck/><span>Продукционният достъп ще бъде ограничен до конкретните служебни акаунти на „Банско за теб“.</span></div><div className="dashboard-stat-grid"><div><Heart/><span>Кампании</span><strong>{campaigns.length}</strong></div><div><Store/><span>Кутии</span><strong>{demoPartners.length}</strong></div><div><CircleDollarSign/><span>Дарения</span><strong>—</strong></div></div><div className="dashboard-section-head"><div><h3>Кампании</h3><p>Тествай редакция на заглавието и запазване.</p></div><button className="outline-small" onClick={resetDemo}>Нулирай демото</button></div>{saved&&<div className="saved-message"><Check/> Промяната е запазена.</div>}<div className="dashboard-list">{campaigns.map(c=><div className="dashboard-item" key={c.id}>{editingId===c.id?<div className="edit-row"><input value={draftTitle} onChange={e=>setDraftTitle(e.target.value)}/><button className="primary-btn compact" onClick={saveCampaign}>Запази</button><button className="ghost-btn" onClick={()=>setEditingId(null)}>Отказ</button></div>:<><div><span className="tiny-status">{c.status}</span><strong>{c.title}</strong></div><button className="edit-btn" onClick={()=>editCampaign(c)}><Pencil/> Редакция</button></>}</div>)}</div></div></div>}
  <button className="floating-donate" onClick={()=>goTo('donate')}><Heart/> Дарете</button>
 </div>
}
